#!/bin/bash
# Render layout JSON into tiny-dfr config and optional Hyprland binds.
set -euo pipefail

PLUGIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
USER_LAYOUT="${OMARCHY_TOUCHBAR_LAYOUT:-$HOME/.config/omarchy/touchbar.json}"
STOCK_LAYOUT="$PLUGIN_DIR/layout.json"
BINDINGS="${OMARCHY_TOUCHBAR_BINDINGS:-$HOME/.config/hypr/bindings.lua}"
ETC_CONF="${OMARCHY_TOUCHBAR_ETC:-/etc/tiny-dfr/config.toml}"
MARKER_BEGIN="-- io.github.austindixson.touchbar begin"
MARKER_END="-- io.github.austindixson.touchbar end"
GENERATED_MARK="Generated by io.github.austindixson.touchbar"

if [[ -f $USER_LAYOUT ]]; then
  LAYOUT=$USER_LAYOUT
else
  LAYOUT=$STOCK_LAYOUT
fi

[[ -f $LAYOUT ]] || exit 0
command -v python3 >/dev/null || exit 0

toml_out=$(mktemp)
trap 'rm -f "$toml_out"' EXIT

python3 - "$LAYOUT" "$BINDINGS" "$MARKER_BEGIN" "$MARKER_END" "$GENERATED_MARK" "$toml_out" <<'PY'
import json, os, sys

layout_path, bindings_path, begin, end, mark, toml_out = sys.argv[1:7]
layout = json.loads(open(layout_path).read())

def toml_btn(btn):
    key = btn.get("key")
    if isinstance(key, list):
        action = "[" + ", ".join(f'"{k}"' for k in key) + "]"
    else:
        action = f'"{key}"'
    parts = [f"Action = {action}"]
    if btn.get("icon"):
        parts.insert(0, f'Icon = "{btn["icon"]}"')
    elif btn.get("text"):
        parts.insert(0, f'Text = "{btn["text"]}"')
    if btn.get("stretch"):
        parts.append(f"Stretch = {int(btn['stretch'])}")
    return "    { " + ", ".join(parts) + " }"

def layer(name, buttons):
    rows = ",\n".join(toml_btn(b) for b in buttons if b.get("key"))
    return f"{name} = [\n{rows}\n]\n"

media = layout.get("buttons") or []
fn = layout.get("fnLayer") or []
media_default = "true" if layout.get("mediaLayerDefault", True) else "false"
outlines = "true" if layout.get("showButtonOutlines", True) else "false"
adaptive = "true" if layout.get("adaptiveBrightness", True) else "false"

toml = f"""# {mark}
MediaLayerDefault = {media_default}
ShowButtonOutlines = {outlines}
EnablePixelShift = false
FontTemplate = ":bold"
AdaptiveBrightness = {adaptive}
ActiveBrightness = 128

{layer("PrimaryLayerKeys", fn)}
{layer("MediaLayerKeys", media)}
"""
open(toml_out, "w").write(toml)

bind_lines = [begin, f"-- {mark}"]
seen = set()
for btn in media:
    hypr = btn.get("hyprKey")
    cmd = btn.get("command")
    if not hypr or not cmd or hypr in seen:
        continue
    seen.add(hypr)
    desc = btn.get("text") or btn.get("icon") or hypr
    bind_lines.append(f'o.bind("{hypr}", "Touch Bar {desc}", "{cmd}")')
bind_lines.append(end)
block = "\n".join(bind_lines) + "\n"

if os.path.isfile(bindings_path) and seen:
    text = open(bindings_path).read()
    if begin in text and end in text:
        pre = text.split(begin, 1)[0].rstrip() + "\n\n"
        post = text.split(end, 1)[1].lstrip("\n")
        text = pre + block + ("\n" + post if post else "")
    else:
        text = text.rstrip() + "\n\n" + block
    open(bindings_path, "w").write(text)
PY

[[ ${OMARCHY_TOUCHBAR_SKIP_INSTALL:-} == 1 ]] && exit 0

if [[ -f $ETC_CONF ]] && cmp -s "$toml_out" "$ETC_CONF"; then
  exit 0
fi

if [[ -f $ETC_CONF ]] &&
  ! grep -Fq "$GENERATED_MARK" "$ETC_CONF" &&
  ! grep -Fq "Omarchy Apple Silicon Touch Bar" "$ETC_CONF"; then
  echo "apply.sh: leaving $ETC_CONF in place (not generated by this plugin)" >&2
  exit 0
fi

# Quickshell has no terminal. sudo from a detached process fails silently once
# the ticket is cold; pkexec puts up a polkit prompt. sudo stays for a real TTY.
run_as_root() {
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
    "$@"
  elif [[ -t 0 && -t 1 ]]; then
    sudo "$@"
  else
    command -v pkexec >/dev/null || {
      echo "io.github.austindixson.touchbar: pkexec is required to install the Touch Bar layout" >&2
      exit 1
    }
    pkexec "$@"
  fi
}

install_bin=$(command -v install)
systemctl_bin=$(command -v systemctl || true)
install_cmd="$(printf '%q' "$install_bin") -D -m 644 $(printf '%q' "$toml_out") $(printf '%q' "$ETC_CONF")"
if [[ -n $systemctl_bin ]]; then
  install_cmd+=" && $(printf '%q' "$systemctl_bin") restart tiny-dfr.service"
fi

run_as_root /bin/bash -c "$install_cmd"
