#!/bin/bash
# Render layout JSON into tiny-dfr config and optional Hyprland binds.
set -euo pipefail

PLUGIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
USER_LAYOUT="${OMARCHY_TOUCHBAR_LAYOUT:-$HOME/.config/omarchy/touchbar.json}"
STOCK_LAYOUT="$PLUGIN_DIR/layout.json"
BINDINGS="${OMARCHY_TOUCHBAR_BINDINGS:-$HOME/.config/hypr/bindings.lua}"
ETC_CONF="${OMARCHY_TOUCHBAR_ETC:-/etc/tiny-dfr/config.toml}"
MARKER_BEGIN="-- io.github.austindixson.touchbar begin"
MARKER_END="-- io.github.austindixson.touchbar end"
GENERATED_MARK="Generated by io.github.austindixson.touchbar"

# Layout files are capped at 64 KiB and must be regular files; symlinks are
# refused outright (marketplace #6878). Checks use lstat/stat only, so a FIFO
# at the layout path is rejected without ever being opened.
MAX_LAYOUT_BYTES=65536

# The Hyprland bindings file is user-controlled too (marketplace #9252). It is
# read through a bounded, no-follow, non-blocking open and rewritten via an
# exclusive temp file plus atomic rename, never truncated in place.
MAX_BINDINGS_BYTES=262144

validate_layout_file() {
  local path=$1
  local label=${2:-layout}
  local size
  if [[ -L $path ]]; then
    echo "apply.sh: refusing symlink $label (marketplace #6878): $path" >&2
    return 1
  fi
  if [[ ! -e $path ]]; then
    echo "apply.sh: $label not found: $path" >&2
    return 1
  fi
  if [[ ! -f $path ]]; then
    echo "apply.sh: $label must be a regular file (not FIFO/dir/device): $path" >&2
    return 1
  fi
  size=$(stat -c '%s' -- "$path" 2>/dev/null || stat -f '%z' -- "$path" 2>/dev/null) || size=
  if [[ ! $size =~ ^[0-9]+$ ]]; then
    echo "apply.sh: cannot stat $label: $path" >&2
    return 1
  fi
  if (( size > MAX_LAYOUT_BYTES )); then
    echo "apply.sh: $label too large (max $MAX_LAYOUT_BYTES bytes): $path ($size bytes)" >&2
    return 1
  fi
}

# -L first: a dangling symlink is not -e but must still fail closed.
if [[ -L $USER_LAYOUT || -e $USER_LAYOUT ]]; then
  validate_layout_file "$USER_LAYOUT" "user layout" || exit 1
  LAYOUT=$USER_LAYOUT
else
  validate_layout_file "$STOCK_LAYOUT" "stock layout" || exit 1
  LAYOUT=$STOCK_LAYOUT
fi

command -v python3 >/dev/null || exit 0

toml_out=$(mktemp)
trap 'rm -f "$toml_out"' EXIT

python3 - "$LAYOUT" "$BINDINGS" "$MARKER_BEGIN" "$MARKER_END" "$GENERATED_MARK" "$toml_out" "$MAX_LAYOUT_BYTES" "$MAX_BINDINGS_BYTES" <<'PY'
import json, os, secrets, stat, sys

layout_path, bindings_path, begin, end, mark, toml_out = sys.argv[1:7]
max_bytes = int(sys.argv[7])
max_bindings_bytes = int(sys.argv[8])

def read_regular_file(path, limit, label):
    # O_NOFOLLOW refuses a symlink at the final component; O_NONBLOCK keeps
    # open() from stalling on a FIFO. The type and size are checked on the
    # opened fd, so a swap after any earlier check cannot get past them.
    # Returns None only when the path does not exist.
    flags = os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK | os.O_CLOEXEC
    flags |= getattr(os, "O_NOCTTY", 0)
    try:
        fd = os.open(path, flags)
    except FileNotFoundError:
        return None, None
    except OSError as e:
        sys.exit(f"apply.sh: cannot open {label} safely: {path}: {e.strerror}")
    try:
        st = os.fstat(fd)
        if not stat.S_ISREG(st.st_mode):
            sys.exit(f"apply.sh: {label} must be a regular file: {path}")
        if st.st_size > limit:
            sys.exit(f"apply.sh: {label} too large (max {limit} bytes): {path}")
        chunks = []
        total = 0
        while total <= limit:
            chunk = os.read(fd, min(65536, limit + 1 - total))
            if not chunk:
                break
            chunks.append(chunk)
            total += len(chunk)
    except OSError as e:
        sys.exit(f"apply.sh: cannot read {label}: {path}: {e.strerror}")
    finally:
        os.close(fd)
    if total > limit:
        sys.exit(f"apply.sh: {label} too large (max {limit} bytes): {path}")
    return b"".join(chunks), st

def read_layout(path):
    data, _ = read_regular_file(path, max_bytes, "layout")
    if data is None:
        sys.exit(f"apply.sh: layout not found: {path}")
    return data.decode("utf-8")

def write_atomic(path, data, st):
    # Exclusive, no-follow temp file in the same directory, then rename over
    # the destination. rename replaces a symlink at `path` instead of writing
    # through it, and readers never see a truncated file.
    directory = os.path.dirname(path) or "."
    tmp = os.path.join(
        directory, f".{os.path.basename(path)}.tmp.{os.getpid()}.{secrets.token_hex(8)}")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL | os.O_NOFOLLOW | os.O_CLOEXEC
    try:
        fd = os.open(tmp, flags, 0o600)
    except OSError as e:
        sys.exit(f"apply.sh: cannot create temp file next to bindings: {tmp}: {e.strerror}")
    try:
        try:
            os.fchmod(fd, stat.S_IMODE(st.st_mode))
            view = memoryview(data)
            while view:
                view = view[os.write(fd, view):]
            os.fsync(fd)
        finally:
            os.close(fd)
        cur = os.lstat(path)
        if not stat.S_ISREG(cur.st_mode) or (cur.st_dev, cur.st_ino) != (st.st_dev, st.st_ino):
            sys.exit(f"apply.sh: bindings changed while updating, refusing: {path}")
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise
    try:
        dfd = os.open(directory, os.O_RDONLY | os.O_DIRECTORY | os.O_CLOEXEC)
        try:
            os.fsync(dfd)
        finally:
            os.close(dfd)
    except OSError:
        pass

layout = json.loads(read_layout(layout_path))

def toml_btn(btn):
    key = btn.get("key")
    if isinstance(key, list):
        action = "[" + ", ".join(f'"{k}"' for k in key) + "]"
    else:
        action = f'"{key}"'
    parts = [f"Action = {action}"]
    if btn.get("icon"):
        parts.insert(0, f'Icon = "{btn["icon"]}"')
    elif btn.get("text"):
        parts.insert(0, f'Text = "{btn["text"]}"')
    if btn.get("stretch"):
        parts.append(f"Stretch = {int(btn['stretch'])}")
    return "    { " + ", ".join(parts) + " }"

def layer(name, buttons):
    rows = ",\n".join(toml_btn(b) for b in buttons if b.get("key"))
    return f"{name} = [\n{rows}\n]\n"

media = layout.get("buttons") or []
fn = layout.get("fnLayer") or []
media_default = "true" if layout.get("mediaLayerDefault", True) else "false"
outlines = "true" if layout.get("showButtonOutlines", True) else "false"
adaptive = "true" if layout.get("adaptiveBrightness", True) else "false"

toml = f"""# {mark}
MediaLayerDefault = {media_default}
ShowButtonOutlines = {outlines}
EnablePixelShift = false
FontTemplate = ":bold"
AdaptiveBrightness = {adaptive}
ActiveBrightness = 128

{layer("PrimaryLayerKeys", fn)}
{layer("MediaLayerKeys", media)}
"""
open(toml_out, "w").write(toml)

bind_lines = [begin, f"-- {mark}"]
seen = set()
for btn in media:
    hypr = btn.get("hyprKey")
    cmd = btn.get("command")
    if not hypr or not cmd or hypr in seen:
        continue
    seen.add(hypr)
    desc = btn.get("text") or btn.get("icon") or hypr
    bind_lines.append(f'o.bind("{hypr}", "Touch Bar {desc}", "{cmd}")')
bind_lines.append(end)
block = "\n".join(bind_lines) + "\n"

if seen:
    raw, bindings_st = read_regular_file(bindings_path, max_bindings_bytes, "bindings")
else:
    raw, bindings_st = None, None

if raw is not None:
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        sys.exit(f"apply.sh: bindings is not valid UTF-8: {bindings_path}")
    if begin in text and end in text:
        pre = text.split(begin, 1)[0].rstrip() + "\n\n"
        post = text.split(end, 1)[1].lstrip("\n")
        text = pre + block + ("\n" + post if post else "")
    else:
        text = text.rstrip() + "\n\n" + block
    write_atomic(bindings_path, text.encode("utf-8"), bindings_st)
PY

[[ ${OMARCHY_TOUCHBAR_SKIP_INSTALL:-} == 1 ]] && exit 0

if [[ -f $ETC_CONF ]] && cmp -s "$toml_out" "$ETC_CONF"; then
  exit 0
fi

if [[ -f $ETC_CONF ]] &&
  ! grep -Fq "$GENERATED_MARK" "$ETC_CONF" &&
  ! grep -Fq "Omarchy Apple Silicon Touch Bar" "$ETC_CONF"; then
  echo "apply.sh: leaving $ETC_CONF in place (not generated by this plugin)" >&2
  exit 0
fi

# Privilege-boundary helpers must come from known system paths, never PATH.
# A user-writable PATH entry would otherwise run as root after pkexec/sudo.
system_bin() {
  local name=$1
  local candidate
  for candidate in "/usr/bin/$name" "/bin/$name" "/usr/sbin/$name" "/sbin/$name"; do
    if [[ -x "$candidate" && -f "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  echo "io.github.austindixson.touchbar: missing system $name" >&2
  exit 1
}

# Quickshell has no terminal. sudo from a detached process fails silently once
# the ticket is cold; pkexec puts up a polkit prompt. sudo stays for a real TTY.
run_as_root() {
  local elev_bin
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
    "$@"
  elif [[ -t 0 && -t 1 ]]; then
    elev_bin=$(system_bin sudo)
    "$elev_bin" "$@"
  else
    elev_bin=$(system_bin pkexec)
    "$elev_bin" "$@"
  fi
}

install_bin=$(system_bin install)
systemctl_bin=$(system_bin systemctl)
bash_bin=$(system_bin bash)
install_cmd="$(printf '%q' "$install_bin") -D -m 644 $(printf '%q' "$toml_out") $(printf '%q' "$ETC_CONF")"
install_cmd+=" && $(printf '%q' "$systemctl_bin") restart tiny-dfr.service"

run_as_root "$bash_bin" -c "$install_cmd"
