#!/bin/bash
# Render layout JSON into tiny-dfr config and optional Hyprland binds.
set -euo pipefail

PLUGIN_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
USER_LAYOUT="${OMARCHY_TOUCHBAR_LAYOUT:-$HOME/.config/omarchy/touchbar.json}"
STOCK_LAYOUT="$PLUGIN_DIR/layout.json"
BINDINGS="${OMARCHY_TOUCHBAR_BINDINGS:-$HOME/.config/hypr/bindings.lua}"
ETC_CONF="${OMARCHY_TOUCHBAR_ETC:-/etc/tiny-dfr/config.toml}"
MARKER_BEGIN="-- io.github.austindixson.touchbar begin"
MARKER_END="-- io.github.austindixson.touchbar end"
GENERATED_MARK="Generated by io.github.austindixson.touchbar"

# Layout files are capped at 64 KiB and must be regular files; symlinks are
# refused outright (marketplace #6878). Checks use lstat/stat only, so a FIFO
# at the layout path is rejected without ever being opened.
MAX_LAYOUT_BYTES=65536

validate_layout_file() {
  local path=$1
  local label=${2:-layout}
  local size
  if [[ -L $path ]]; then
    echo "apply.sh: refusing symlink $label (marketplace #6878): $path" >&2
    return 1
  fi
  if [[ ! -e $path ]]; then
    echo "apply.sh: $label not found: $path" >&2
    return 1
  fi
  if [[ ! -f $path ]]; then
    echo "apply.sh: $label must be a regular file (not FIFO/dir/device): $path" >&2
    return 1
  fi
  size=$(stat -c '%s' -- "$path" 2>/dev/null || stat -f '%z' -- "$path" 2>/dev/null) || size=
  if [[ ! $size =~ ^[0-9]+$ ]]; then
    echo "apply.sh: cannot stat $label: $path" >&2
    return 1
  fi
  if (( size > MAX_LAYOUT_BYTES )); then
    echo "apply.sh: $label too large (max $MAX_LAYOUT_BYTES bytes): $path ($size bytes)" >&2
    return 1
  fi
}

# -L first: a dangling symlink is not -e but must still fail closed.
if [[ -L $USER_LAYOUT || -e $USER_LAYOUT ]]; then
  validate_layout_file "$USER_LAYOUT" "user layout" || exit 1
  LAYOUT=$USER_LAYOUT
else
  validate_layout_file "$STOCK_LAYOUT" "stock layout" || exit 1
  LAYOUT=$STOCK_LAYOUT
fi

command -v python3 >/dev/null || exit 0

toml_out=$(mktemp)
trap 'rm -f "$toml_out"' EXIT

python3 - "$LAYOUT" "$BINDINGS" "$MARKER_BEGIN" "$MARKER_END" "$GENERATED_MARK" "$toml_out" "$MAX_LAYOUT_BYTES" <<'PY'
import json, os, stat, sys

layout_path, bindings_path, begin, end, mark, toml_out = sys.argv[1:7]
max_bytes = int(sys.argv[7])

def read_layout(path):
    # Re-check on the opened fd so a swap after the shell check cannot
    # substitute a symlink, FIFO, or oversized file.
    try:
        fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW | os.O_NONBLOCK)
    except OSError as e:
        sys.exit(f"apply.sh: cannot open layout safely: {path}: {e.strerror}")
    with os.fdopen(fd, "rb") as f:
        st = os.fstat(f.fileno())
        if not stat.S_ISREG(st.st_mode):
            sys.exit(f"apply.sh: layout must be a regular file: {path}")
        data = f.read(max_bytes + 1)
    if len(data) > max_bytes:
        sys.exit(f"apply.sh: layout too large (max {max_bytes} bytes): {path}")
    return data.decode("utf-8")

layout = json.loads(read_layout(layout_path))

def toml_btn(btn):
    key = btn.get("key")
    if isinstance(key, list):
        action = "[" + ", ".join(f'"{k}"' for k in key) + "]"
    else:
        action = f'"{key}"'
    parts = [f"Action = {action}"]
    if btn.get("icon"):
        parts.insert(0, f'Icon = "{btn["icon"]}"')
    elif btn.get("text"):
        parts.insert(0, f'Text = "{btn["text"]}"')
    if btn.get("stretch"):
        parts.append(f"Stretch = {int(btn['stretch'])}")
    return "    { " + ", ".join(parts) + " }"

def layer(name, buttons):
    rows = ",\n".join(toml_btn(b) for b in buttons if b.get("key"))
    return f"{name} = [\n{rows}\n]\n"

media = layout.get("buttons") or []
fn = layout.get("fnLayer") or []
media_default = "true" if layout.get("mediaLayerDefault", True) else "false"
outlines = "true" if layout.get("showButtonOutlines", True) else "false"
adaptive = "true" if layout.get("adaptiveBrightness", True) else "false"

toml = f"""# {mark}
MediaLayerDefault = {media_default}
ShowButtonOutlines = {outlines}
EnablePixelShift = false
FontTemplate = ":bold"
AdaptiveBrightness = {adaptive}
ActiveBrightness = 128

{layer("PrimaryLayerKeys", fn)}
{layer("MediaLayerKeys", media)}
"""
open(toml_out, "w").write(toml)

bind_lines = [begin, f"-- {mark}"]
seen = set()
for btn in media:
    hypr = btn.get("hyprKey")
    cmd = btn.get("command")
    if not hypr or not cmd or hypr in seen:
        continue
    seen.add(hypr)
    desc = btn.get("text") or btn.get("icon") or hypr
    bind_lines.append(f'o.bind("{hypr}", "Touch Bar {desc}", "{cmd}")')
bind_lines.append(end)
block = "\n".join(bind_lines) + "\n"

if os.path.isfile(bindings_path) and seen:
    text = open(bindings_path).read()
    if begin in text and end in text:
        pre = text.split(begin, 1)[0].rstrip() + "\n\n"
        post = text.split(end, 1)[1].lstrip("\n")
        text = pre + block + ("\n" + post if post else "")
    else:
        text = text.rstrip() + "\n\n" + block
    open(bindings_path, "w").write(text)
PY

[[ ${OMARCHY_TOUCHBAR_SKIP_INSTALL:-} == 1 ]] && exit 0

if [[ -f $ETC_CONF ]] && cmp -s "$toml_out" "$ETC_CONF"; then
  exit 0
fi

if [[ -f $ETC_CONF ]] &&
  ! grep -Fq "$GENERATED_MARK" "$ETC_CONF" &&
  ! grep -Fq "Omarchy Apple Silicon Touch Bar" "$ETC_CONF"; then
  echo "apply.sh: leaving $ETC_CONF in place (not generated by this plugin)" >&2
  exit 0
fi

# Privilege-boundary helpers must come from known system paths, never PATH.
# A user-writable PATH entry would otherwise run as root after pkexec/sudo.
system_bin() {
  local name=$1
  local candidate
  for candidate in "/usr/bin/$name" "/bin/$name" "/usr/sbin/$name" "/sbin/$name"; do
    if [[ -x "$candidate" && -f "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  echo "io.github.austindixson.touchbar: missing system $name" >&2
  exit 1
}

# Quickshell has no terminal. sudo from a detached process fails silently once
# the ticket is cold; pkexec puts up a polkit prompt. sudo stays for a real TTY.
run_as_root() {
  local elev_bin
  if [[ ${EUID:-$(id -u)} -eq 0 ]]; then
    "$@"
  elif [[ -t 0 && -t 1 ]]; then
    elev_bin=$(system_bin sudo)
    "$elev_bin" "$@"
  else
    elev_bin=$(system_bin pkexec)
    "$elev_bin" "$@"
  fi
}

install_bin=$(system_bin install)
systemctl_bin=$(system_bin systemctl)
bash_bin=$(system_bin bash)
install_cmd="$(printf '%q' "$install_bin") -D -m 644 $(printf '%q' "$toml_out") $(printf '%q' "$ETC_CONF")"
install_cmd+=" && $(printf '%q' "$systemctl_bin") restart tiny-dfr.service"

run_as_root "$bash_bin" -c "$install_cmd"
